name: ci

on: [pull_request]
jobs:

  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install necessary tools
        run: make tools

      - name: Run unit tests
        run: make unit-test

      - name: Build the code
        run: make build

      - name: Validate lint
        run: make lint