# (C) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Malware Scan

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
    repository-malware-scan:
      name: "Scan Virus on Repository"
      uses: hpe-actions/malware-scanning/.github/workflows/action.yml@master
